CREATE TABLE mobile_phone
(
    id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    model VARCHAR(50) NOT NULL,
    display VARCHAR(50) NOT NULL,
    length VARCHAR(50) NOT NULL,
    width VARCHAR(50) NOT NULL,
    color VARCHAR(50) NOT NULL,
    price double precision NOT NULL,
    camera VARCHAR(50) NOT NULL
);