CREATE TABLE mobile_phone
(
    id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    model VARCHAR(50) NOT NULL,
    display VARCHAR(50) NOT NULL,
    length VARCHAR(50) NOT NULL,
    width VARCHAR(50) NOT NULL,
    color VARCHAR(50) NOT NULL,
    price double precision NOT NULL,
    camera VARCHAR(50) NOT NULL
);

CREATE TABLE store_order
(
    id bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    address character varying(255) NOT NULL,
    phone character varying(50) NOT NULL,
    delivery_amount double precision NOT NULL,
    additional_info character varying(255)
);

CREATE TABLE commerce_item
(
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    price double precision NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT commerce_item_pkey PRIMARY KEY (order_id, product_id),
    CONSTRAINT commerce_item_order_id_fkey FOREIGN KEY (order_id) REFERENCES store_order (id),
    CONSTRAINT commerce_item_product_id_fkey FOREIGN KEY (product_id) REFERENCES mobile_phone (id)
);

CREATE TABLE fixed_delivery_price
(
    amount double precision NOT NULL
);