spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: admin
    schema: classpath:sql/*-schema.sql
    data: classpath:sql/*-data.sql
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

---

spring:
  profiles: test
  datasource:
    url: jdbc:hsqldb:mem:shop
    username: sa
    password:
    schema: classpath:sql/*-schema-test.sql
  jpa:
    hibernate:
      ddl-auto: create-drop