spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: admin
    schema: classpath:sql/*-schema.sql
    data: classpath:sql/*-data.sql
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        cache:
          region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
server:
  servlet:
    jsp:
      init-parameters:
        development: true
---

spring:
  profiles: test
  datasource:
    url: jdbc:hsqldb:mem:shop
    username: sa
    password:
    schema: classpath:sql/*-schema-test.sql