spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: admin
    schema: classpath:sql/schema/*.sql
    data: classpath:sql/data/*.sql
    initialization-mode: always
  cache:
    ehcache:
      config: classpath:cache/ehcache-store.xml
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: create
    properties:
      net:
        sf:
          ehcache:
            configurationResourceName: cache/ehcache-hibernate.xml
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false
        cache:
          region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
  http:
    encoding:
      force-response: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
server:
  servlet:
    jsp:
      init-parameters:
        development: true