spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: admin
    schema: classpath:sql/*-schema.sql
    data: classpath:sql/*-data.sql
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp